---
layout: post
title: "local な変数に command substitute するときに exit code を判別したい"
date: 2016-10-15 13:46:58
categories: bash
---
<p>bash の local 変数へ command substitution の結果を代入するときに、コマンドが失敗する場合を考慮しようとしたときに、以下の挙動の違いに気がつきました。</p>

<pre><code>#!/bin/bash

func1()  {
    v=$(false)
    echo $?
}

func2() {
    local v=$(false)
    echo $?
}

func1
func2
</code></pre>

<p>実行結果</p>

<pre><code>1
0
</code></pre>

<p>local 変数へバインドするときには、 exit code が何であっても正常終了している様子です。これを、異常終了を検知するうまい方法はないでしょうか。(うまい、の定義が曖昧ならば、一般的にこのようなことをやりたくなった場合の対処方法が何になるのか、が知りたいです。)</p>

<p>普通に考えると、一旦普通の変数へ bind すればいいですが、そもそも関数の中に変数代入の影響範囲を閉じ込めたいから local を使っているのであって、だとすると普通の変数へ bind した途端に local を使う意味が、よくわからなくなってしまいます。</p>
