---
layout: post
title: Python　配列への代入
date: 2017-09-06 06:05:11
categories: python chainer
---
<!-- {% raw %} -->
<p>python2.7を使用しています。<br>
今、下記のコードを実行し、</p>

<pre><code>print r.data
print r[0][action-1].data
</code></pre>

<blockquote>
  <p>[[ 0.34642464  0.39359313 -1.24270797 -0.89923799  0.11451679 -0.49929592]]<br>
  -0.499295920134</p>
</blockquote>

<p>と結果がでました。そこで、</p>

<pre><code>r[0][action-1].data = 1
</code></pre>

<p>と代入を行っても</p>

<pre><code>print r[0][action-1].data
</code></pre>

<blockquote>
  <p>-0.499295920134</p>
</blockquote>

<p>代入が反映されません。何が問題なのでしょうか。<br>
よろしくお願いします。<br>
インポートパッケージは以下です。</p>

<pre><code>import numpy as np　　　　　　　　
import matplotlib.pyplot as plt
import cv2
import random
import chainer
from chainer import cuda
from chainer import serializers
import chainer.functions as F
from chainer import optimizers
</code></pre>

<p>また、<code>print(type(r))</code>を入力すると、</p>

<blockquote>
  <p>class 'chainer.variable.Variable'</p>
</blockquote>

<p>とでます。<code>print　r.dtype</code>結果は</p>

<blockquote>
  <p>float32</p>
</blockquote>

<p>です。　　よろしくお願いします。</p>

<p>　　</p>
<!-- {% endraw %} -->
