---
layout: post
title: AWS SDK for C++ のAws::S3::S3Clientで発生するSEH Exceptionについて
date: 2017-07-31 10:08:02
categories: c++ aws amazon-s3
---
<p>お世話になります。<br>
AWS SDK for C++ を使ってS3にファイルをアップロードする処理を書ています。</p>

<p>・コード</p>

```
    bool hoge()
    {
   　　 Aws::Client::ClientConfiguration config;
    　　config.region = "ap-northeast-1";

   　　 Aws::S3::S3Client　S3Client(Aws::Auth::AWSCredentials
           ("accesskey_id","secret_key", "session_token"), config);

    　　Aws::S3::Model::PutObjectRequest objectRequest;
    　　objectRequest.WithBucket("bucket_key").WithKey("fileName");

    　　objectRequest.SetBody(fileData);

        auto putObjectOutcome = S3Client.PutObject(objectRequest);
　　　　　　 以下省略
}
```

<p>コンパイルは通るのですが、実行した際に上のコードのAws::S3::S3Client S3Client(略)　というコンストラクタに差し掛かったところでエラーが出ます。</p>

<p>・エラー内容</p>

```
初回例外が 0x00007FFCF4A7E48C (aws-cpp-sdk-core.dll) で発生しました (プロジェクト名.exe 内): 0xC0000005: 場所 0x0000000000000000 の読み取り中にアクセス違反が発生しました。
```

<p>gtestを使ってテストを行っているのですが、そのときのエラーとしては</p>

```
unknown file: error : SEH exception with code 0xc0000005 thrown in the test body.
```

<p>が出てFAILEDとなります。</p>

<p>どうやらよくわからないメモリを参照しているようなのですが、原因が不明です。</p>

<p>呼び出し履歴を見るとcrtexe.cのCRTStartup() (626行目)からさらに多く呼び出しが<br>
行われ、最終的に </p>

```
testing::internal::HandleSehExceptionsInMethodIfSupported&lt;class testing::Test,void&gt;(class testing::Test *,void ( testing::Test::*)(void),char const *)  
```

<p>というところで処理が止まります。</p>

<p>調べてみても良い解決策が見つからないため、こちらで質問させていただきます。<br>
何かありましたら補足致します。よろしくお願い致します。</p>
