---
layout: post
title: srez実行で　Failed to remove a directory: train　のエラーの意味と解決法
date: 2017-04-20 21:58:30
categories: python tensorflow
---
<!-- {% raw %} -->
<p>srez実行してもましたが、下記エラー出ました。解決方法がわかりません。<br>
どなたか、アドバイスいただきたいです。 </p>

<p>※srez<br>
<a href="https://github.com/david-gpu/srez" rel="nofollow noreferrer">https://github.com/david-gpu/srez</a></p>

<p><code>C:\Users\wai\Documents\srez&gt;python srez_main.py --run train</code> を実行</p>

<p>エラー</p>

<pre><code>C:\Users\wai\Documents\srez&gt;python srez_main.py --run train
Traceback (most recent call last):
  File "srez_main.py", line 190, in &lt;module&gt;
    tf.app.run()
  File "C:\Users\wai\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "srez_main.py", line 187, in main
    _train()
  File "srez_main.py", line 145, in _train
    all_filenames = prepare_dirs(delete_train_dir=True)
  File "srez_main.py", line 75, in prepare_dirs
    tf.gfile.DeleteRecursively(FLAGS.train_dir)
  File "C:\Users\wai\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 366, in delete_recursively
    pywrap_tensorflow.DeleteRecursively(compat.as_bytes(dirname), status)
  File "C:\Users\wai\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\wai\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to remove a directory: train
</code></pre>

<p>実行環境は下記のとおりです。<br>
ＯＳ：Win8.1<br>
Anaconda Nvigator 1.3.1　使用<br>
python 3.5.2<br>
tensorflow 1.0.1</p>

<p>ディレクトリ構成は下記です。</p>

<p><a href="https://i.stack.imgur.com/8bd4Q.jpg" rel="nofollow noreferrer"><img src="https://i.stack.imgur.com/8bd4Q.jpg" alt="画像の説明をここに入力"></a></p>
<!-- {% endraw %} -->
