---
layout: post
title: Pythonのurllib.request.Requestでheadersを指定しても反映されない?
date: 2018-11-25 12:42:56
categories: python python3
---
<p>Python3の<code>urllib.request.Request</code>のheadersでhttp headerを指定してもheaderが送信されないのですがなぜこのようなことがおこるのでしょうか?</p>

<p>mnctf2017というctfサイトの情報照会というお題に取り組んでいるのですが、この問題では、FLAGをとるためにAPIサーバに問い合わせる必要があります。<br>
APIにアクセスするためにはAPI tokenのようなものを<code>X-TOKEN</code>ヘッダに追加しなければなりません。<br>
X-TOKENヘッダを追加するためにurllib.request.Requestの引数のheadersに<code>{"X-TOKEN": token}</code>としてリクエストを送信するのですが、X-TOKENをヘッダに追加したにもかかわらず、X-TOKENがないというエラーが返ってきます。</p>

<p>なぜでしょうか?</p>

<p>ちなみに他の方の答えを見たところrequestsをつかうとうまくいくようです。</p>

<p>urllibを使ってアクセスするコード:</p>

<pre>
<code>
import urllib.request as ur
import urllib.parse as up
import time
import json

hashlist = open("minhashlist.txt").read().split("\n")[:-1]
malware_name = "RAT.A.aa74e"
apikey = "578459a056231ac6745fcb53e3304b3043bb7c9448863e84652764592d15b3d1"

def get_apitoken():
    post_data = up.urlencode({"key": apikey}).encode("utf-8")
    res = ur.urlopen("http://157.7.53.197/intel/gettoken/", data=post_data)
    res_str = res.read().decode("ascii")
    res_json = json.loads(res_str)
    return res_json["expire"], res_json["token"]

def search(token, hash):
    print(token)
    data = up.urlencode({"hash": hash}).encode("utf-8")
    req = ur.Request("http://157.7.53.197/intel/query/", data=data, headers={
        "x-token": token # ここで"X-TOKEN"を追加した
        })
    res = ur.urlopen(req)
    body = res.read().decode("utf-8")
    res_json = json.loads(body)
    if res_json["auth"] != "success": #認証に失敗したらエラーを発生させる
        raise Exception("auth error: " + res_json["reason"])
    if malware_name in detection_name:
        print("answer:", res_json["hash"])

def main():
    expire, token = get_apitoken()
    expire = int(expire)
    for v in hashlist:
        search(token, v)
        now = time.time()
        if now >= expired:
            expire, token = get_apitoken()
            expire = int(expire)
</code>
</pre>

<p>エラーメッセージ:</p>

```
Traceback (most recent call last):
  File "getinfo.py", line 41, in &lt;module&gt;
    main()
  File "getinfo.py", line 35, in main
    search(token, v)
  File "getinfo.py", line 27, in search
    raise Exception("auth error: " + res_json["reason"])
Exception: auth error: no x-token header
```

<p><a href="http://mnctf.info/mnctf2017/top.php" rel="nofollow noreferrer">http://mnctf.info/mnctf2017/top.php</a><br>
[上のURLの"情報照会"という問題です]</p>

<p>このCTFで使用するAPIサーバの仕様書<br>
<a href="http://mnctf.info/mnctf2017/task/MiNTEL_API_Reference.pdf" rel="nofollow noreferrer">http://mnctf.info/mnctf2017/task/MiNTEL_API_Reference.pdf</a></p>

<p>環境: <br>
Windows 10<br>
Python 3.6.7</p>
