---
layout: post
title: "subprocessで外部プログラムから正しい値が返ってこない。"
date: 2019-03-24 13:16:19
categories: python python3 line
---
<p>Line messaging APIを使って気温を通知するのに挑戦しています。<a href="https://github.com/line/line-bot-sdk-python/blob/master/examples/flask-kitchensink/app.py" rel="nofollow noreferrer">こちら</a>のサンプルプログラムに下記コードを追加しLINEから"気温"と実行したらエラーが吐き出されました。どうすれば気温が通知されるでしょうか？</p>

<h3>app.py</h3>

<pre><code>elif text == '気温':
        cmd = ["python3", "dth11.py"]
        proc = subprocess.Popen(cmd, stdout=subprocess.PIPE,
               stderr=subprocess.STDOUT)
        temp = proc.stdout.read().decode("utf-8")
        line_bot_api.reply_message(event.reply_token, TextSendMessage(text=temp))
</code></pre>

<h3>dth11.py</h3>

<pre><code>import Adafruit_DHT as DHT

SENSOR_TYPE = DHT.DHT11
DHT_GPIO = 22
h,t = DHT.read_retry(SENSOR_TYPE, DHT_GPIO)
print("現在の部屋の気温は{0:0.1f}度、湿度{1:0.1f}%です。".format(t,h))
</code></pre>

<h3>エラー内容</h3>

<pre><code>python3: can't open file 'dth11.py': [Errno 2] No such file or directory
</code></pre>

<p>app.pyとdth11.pyは同じディレクトリに置いてあります。よろしくお願いします。</p>
