---
layout: post
title: "画像読み込み時の Permission denied に関して"
date: 2019-10-01 05:44:09
categories: python windows twitter
---
<p>python初心者です。<br>
画像tweetしようと以下.pyを作成しました。</p>

<pre><code>#!/usr/bin/env python
# coding: utf-8

import json
from requests_oauthlib import OAuth1Session

CK = '# Consumer Key' # Consumer Key
CS = '# Consumer Secret' # Consumer Secret
AT = '# Access Token' # Access Token
AS = ' # Accesss Token' # Accesss Token Secert

# 画像とテキストのURL
url_media = "https://upload.twitter.com/1.1/media/upload.json"
url_text = "https://api.twitter.com/1.1/statuses/update.json"

# 認証
twitter = OAuth1Session(CK, CS, AT, AS)

# 画像投稿
path = "# 画像ファイルのパス" # 画像ファイルのパス
files = {"media" : open(path, 'rb')}
req_media = twitter.post(url_media, files = files)

# レスポンスを確認
if req_media.status_code != 200:
 print ("Upload image is Failed: %s", req_media.text)
exit()

# IDを取得
media_id = json.loads(req_media.text)['media_id']
print ("Media ID: %d" % media_id)

# IDを付加してテキストを投稿
params = {'status': '#splatoon2 #NintendoSwitch', "media_ids": [media_id]}
req_media = twitter.post(url_text, params = params)

# レスポンスを確認
if req_media.status_code != 200:
 print ("Upload text is Failed: %s", req_text.text)
exit()

print ("OK")
</code></pre>

<p>上記を実行すると以下のコメントが出てきます。<br>
Cドライブ-デスクトップ配下に画像フォルダがあるのですが、<br>
読み込み専用も解除しているのですが、どうしたら分からず。。<br>
ご教示頂けますと幸いです。</p>

<pre><code>Traceback (most recent call last):
  File "imagetweet.py", line 21, in &lt;module&gt;
    files = {"media" : open(path, 'rb')}
PermissionError: [Errno 13] Permission denied: '# 画像ファイルのパス'
</code></pre>
